// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Map/MapMarkerPlacementTool.layout

class PR_MapMarkerPlacementToolWidgets
{
	static const ResourceName s_sLayout = "{8D12ABB2B0743BF8}UI/Map/MapMarkerPlacementTool.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_MarkerTextEditBox;
	SCR_EditBoxComponent m_MarkerTextEditBoxComponent;

	OverlayWidget m_VisibilityListbox;
	SCR_ListBoxComponent m_VisibilityListboxComponent;

	VerticalLayoutWidget m_ColorSelectionVerticalLayout;

	VerticalLayoutWidget m_IconSelectionVerticalLayout;

	ButtonWidget m_CancelButton;
	SCR_ButtonTextComponent m_CancelButtonComponent;

	ButtonWidget m_OkButton;
	SCR_ButtonTextComponent m_OkButtonComponent;

	bool Init(Widget root)
	{
		m_MarkerTextEditBox = ButtonWidget.Cast(root.FindAnyWidget("m_MarkerTextEditBox"));
		m_MarkerTextEditBoxComponent = SCR_EditBoxComponent.Cast(m_MarkerTextEditBox.FindHandler(SCR_EditBoxComponent));

		m_VisibilityListbox = OverlayWidget.Cast(root.FindAnyWidget("m_VisibilityListbox"));
		m_VisibilityListboxComponent = SCR_ListBoxComponent.Cast(m_VisibilityListbox.FindHandler(SCR_ListBoxComponent));

		m_ColorSelectionVerticalLayout = VerticalLayoutWidget.Cast(root.FindAnyWidget("m_ColorSelectionVerticalLayout"));

		m_IconSelectionVerticalLayout = VerticalLayoutWidget.Cast(root.FindAnyWidget("m_IconSelectionVerticalLayout"));

		m_CancelButton = ButtonWidget.Cast(root.FindAnyWidget("m_CancelButton"));
		m_CancelButtonComponent = SCR_ButtonTextComponent.Cast(m_CancelButton.FindHandler(SCR_ButtonTextComponent));

		m_OkButton = ButtonWidget.Cast(root.FindAnyWidget("m_OkButton"));
		m_OkButtonComponent = SCR_ButtonTextComponent.Cast(m_OkButton.FindHandler(SCR_ButtonTextComponent));

		return true;
	}
}
