// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/FactionSelectionMenu/FactionSelectionButton.layout

class PR_FactionSelectionButtonWidgets
{
	static const ResourceName s_sLayout = "{51A47649B4BDA716}UI/FactionSelectionMenu/FactionSelectionButton.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_FlagImage;

	TextWidget m_FactionNameText;

	TextWidget m_PlayerCountText;

	bool Init(Widget root)
	{
		m_FlagImage = ImageWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.VerticalLayout0.HorizontalLayout0.m_FlagImage"));

		m_FactionNameText = TextWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.VerticalLayout0.HorizontalLayout0.m_FactionNameText"));

		m_PlayerCountText = TextWidget.Cast(root.FindWidget("SizeLayout0.Overlay0.VerticalLayout0.m_PlayerCountText"));

		return true;
	}
}
