// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/FactionSelectionMenu/FactionSelectionMenu.layout

class PR_FactionSelectionMenuWidgets
{
	static const ResourceName s_sLayout = "{FAF119E75E0B9EBD}UI/FactionSelectionMenu/FactionSelectionMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ButtonWidget m_Faction0Button;
	SCR_ModularButtonComponent m_Faction0ButtonComponent;

	ButtonWidget m_Faction1Button;
	SCR_ModularButtonComponent m_Faction1ButtonComponent;

	bool Init(Widget root)
	{
		m_Faction0Button = ButtonWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.SizeLayout0.VerticalLayout0.m_Faction0Button"));
		m_Faction0ButtonComponent = SCR_ModularButtonComponent.Cast(m_Faction0Button.FindHandler(SCR_ModularButtonComponent));

		m_Faction1Button = ButtonWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.SizeLayout0.VerticalLayout0.m_Faction1Button"));
		m_Faction1ButtonComponent = SCR_ModularButtonComponent.Cast(m_Faction1Button.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
