modded enum SCR_DebugMenuID
{
	REFINE_MENU_ID,
	REFINE_SHOW_CAPTURE_AREA_STATE,
	REFINE_SHOW_ASSET_SPAWNER_STATE,
	REFINE_SHOW_SPAWN_POINT_STATE,
	REFINE_SHOW_BUILDING_PROVIDER_STATE,
	REFINE_SHOW_SUPPLY_HOLDER_INFO,
	
	REFINE_GAME_MODE_PANEL,
	REFINE_OPEN_BUILDING_DISPLAY,
	REFINE_OPEN_DEPLOYMENT_MENU,
	REFINE_OPEN_FACTION_MENU,
	
	REFINE_DISABLE_DEPLOYMENT_COUNTDOWN,
	REFINE_DISABLE_AUTO_DEPLOYMENT_MENU,
	
	REFINE_HOLDER_IDX,
	REFINE_TARGET_IDX,
	REFINE_SUPPLY_AMOUNT,
	REFINE_GIVE_SUPPLY,
	REFINE_TAKE_SUPPLY
}