// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/GameModeDisplay/GameModeDisplay.layout

class PR_GameModeDisplayWidgets
{
	static const ResourceName s_sLayout = "{92C7C20511C737EE}UI/GameModeDisplay/GameModeDisplay.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_StaticText;

	OverlayWidget m_CurrentAreaOverlay;

	ImageWidget m_AreaFlagImage;

	OverlayWidget m_AreaLock;

	ProgressBarWidget m_AreaProgressBar;

	TextWidget m_AreaNameText;

	bool Init(Widget root)
	{
		m_StaticText = TextWidget.Cast(root.FindWidget("m_StaticText"));

		m_CurrentAreaOverlay = OverlayWidget.Cast(root.FindWidget("m_CurrentAreaOverlay"));

		m_AreaFlagImage = ImageWidget.Cast(root.FindWidget("m_CurrentAreaOverlay.HorizontalLayout.Overlay0.m_AreaFlagImage"));

		m_AreaLock = OverlayWidget.Cast(root.FindWidget("m_CurrentAreaOverlay.HorizontalLayout.Overlay0.m_AreaLock"));

		m_AreaProgressBar = ProgressBarWidget.Cast(root.FindWidget("m_CurrentAreaOverlay.HorizontalLayout.VerticalLayout0.SizeLayout0.Overlay0.m_AreaProgressBar"));

		m_AreaNameText = TextWidget.Cast(root.FindWidget("m_CurrentAreaOverlay.HorizontalLayout.VerticalLayout0.m_AreaNameText"));

		return true;
	}
}
