// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Menus/PlayerList/PlayerListGameModeHeader.layout

class PR_PlayerListGameModeHeaderWidgets
{
	static const ResourceName s_sLayout = "{2C4F6D2F7B3AB380}UI/layouts/Menus/PlayerList/PlayerListGameModeHeader.layout";
	ResourceName GetLayout() { return s_sLayout; }

	ImageWidget m_FactionFlagImage;

	TextWidget m_FactionScoreText;

	bool Init(Widget root)
	{
		m_FactionFlagImage = ImageWidget.Cast(root.FindAnyWidget("m_FactionFlagImage"));

		m_FactionScoreText = TextWidget.Cast(root.FindAnyWidget("m_FactionScoreText"));

		return true;
	}
}
