// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/layouts/Map/MapMarkerPlacementTool.layout

class PR_MapMarkerPlacementToolWidgets
{
	static const ResourceName s_sLayout = "{8D12ABB2B0743BF8}UI/layouts/Map/MapMarkerPlacementTool.layout";
	ResourceName GetLayout() { return s_sLayout; }

	EditBoxWidget m_MarkerTextEditbox;

	ButtonWidget m_CancelButton;
	SCR_ButtonTextComponent m_CancelButtonComponent;

	ButtonWidget m_OkButton;
	SCR_ButtonTextComponent m_OkButtonComponent;

	bool Init(Widget root)
	{
		m_MarkerTextEditbox = EditBoxWidget.Cast(root.FindAnyWidget("m_MarkerTextEditbox"));

		m_CancelButton = ButtonWidget.Cast(root.FindAnyWidget("m_CancelButton"));
		m_CancelButtonComponent = SCR_ButtonTextComponent.Cast(m_CancelButton.FindHandler(SCR_ButtonTextComponent));

		m_OkButton = ButtonWidget.Cast(root.FindAnyWidget("m_OkButton"));
		m_OkButtonComponent = SCR_ButtonTextComponent.Cast(m_OkButton.FindHandler(SCR_ButtonTextComponent));

		return true;
	}
}
