// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/DeploymentMenu/DeploymentMenu.layout

class PR_DeploymentMenuWidgets
{
	static const ResourceName s_sLayout = "{EC80BA3CC09774C4}UI/DeploymentMenu/DeploymentMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	FrameWidget m_MapFrame;

	OverlayWidget m_MapInteractionArea;

	TextWidget m_DeploymentCountdownText;

	HorizontalLayoutWidget m_Warning;

	TextWidget m_WarningText;

	ButtonWidget m_DeployButton;
	SCR_ModularButtonComponent m_DeployButtonComponent;

	TextWidget m_SpawnPointNameText;

	OverlayWidget m_ChatPanel;
	SCR_ChatPanel m_ChatPanelComponent;

	SizeLayoutWidget m_RoleList;
	PR_RoleListComponent m_RoleListComponent;

	SizeLayoutWidget m_GroupList;
	PR_GroupListComponent m_GroupListComponent;

	bool Init(Widget root)
	{
		m_MapFrame = FrameWidget.Cast(root.FindWidget("m_MapFrame"));

		m_MapInteractionArea = OverlayWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea"));

		m_DeploymentCountdownText = TextWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea.SpawnPointSelection.Overlay.VerticalLayout0.m_DeploymentCountdownText"));

		m_Warning = HorizontalLayoutWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea.SpawnPointSelection.Overlay.VerticalLayout0.m_Warning"));

		m_WarningText = TextWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea.SpawnPointSelection.Overlay.VerticalLayout0.m_Warning.m_WarningText"));

		m_DeployButton = ButtonWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea.SpawnPointSelection.Overlay.VerticalLayout0.HorizontalLayout0.m_DeployButton"));
		m_DeployButtonComponent = SCR_ModularButtonComponent.Cast(m_DeployButton.FindHandler(SCR_ModularButtonComponent));

		m_SpawnPointNameText = TextWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea.SpawnPointSelection.Overlay.VerticalLayout0.HorizontalLayout0.m_SpawnPointNameText"));

		m_ChatPanel = OverlayWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.m_MapInteractionArea.m_ChatPanel"));
		m_ChatPanelComponent = SCR_ChatPanel.Cast(m_ChatPanel.FindHandler(SCR_ChatPanel));

		m_RoleList = SizeLayoutWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.Right.HorizontalLayout0.m_RoleList"));
		m_RoleListComponent = PR_RoleListComponent.Cast(m_RoleList.FindHandler(PR_RoleListComponent));

		m_GroupList = SizeLayoutWidget.Cast(root.FindWidget("SizeBase.VerticalLayout0.ContentOverlay.VerticalLayout.Main.Right.HorizontalLayout0.m_GroupList"));
		m_GroupListComponent = PR_GroupListComponent.Cast(m_GroupList.FindHandler(PR_GroupListComponent));

		return true;
	}
}
