// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/DeploymentMenu/GroupEntry.layout

class PR_GroupEntryWidgets
{
	static const ResourceName s_sLayout = "{E5B94A03AF210305}UI/DeploymentMenu/GroupEntry.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_GroupNameText;

	ButtonWidget m_ExpandButton;
	SCR_ModularButtonComponent m_ExpandButtonComponent;

	TextWidget m_PlayerCountText;

	ButtonWidget m_JoinButton;
	SCR_ModularButtonComponent m_JoinButtonComponent;

	VerticalLayoutWidget m_GroupMemberList;

	bool Init(Widget root)
	{
		m_GroupNameText = TextWidget.Cast(root.FindWidget("VerticalLayout0.HeaderSize.HorizontalLayout0.m_GroupNameText"));

		m_ExpandButton = ButtonWidget.Cast(root.FindWidget("VerticalLayout0.HeaderSize.HorizontalLayout0.m_ExpandButton"));
		m_ExpandButtonComponent = SCR_ModularButtonComponent.Cast(m_ExpandButton.FindHandler(SCR_ModularButtonComponent));

		m_PlayerCountText = TextWidget.Cast(root.FindWidget("VerticalLayout0.HeaderSize.HorizontalLayout0.PlayerCount.m_PlayerCountText"));

		m_JoinButton = ButtonWidget.Cast(root.FindWidget("VerticalLayout0.HeaderSize.HorizontalLayout0.m_JoinButton"));
		m_JoinButtonComponent = SCR_ModularButtonComponent.Cast(m_JoinButton.FindHandler(SCR_ModularButtonComponent));

		m_GroupMemberList = VerticalLayoutWidget.Cast(root.FindWidget("VerticalLayout0.m_GroupMemberList"));

		return true;
	}
}
