// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/DeploymentMenu/GroupList.layout

class PR_GroupListWidgets
{
	static const ResourceName s_sLayout = "{949AC0EDAAE45ED7}UI/DeploymentMenu/GroupList.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_GroupListLayout;

	ButtonWidget m_GroupNameEditBox;
	SCR_EditBoxComponent m_GroupNameEditBoxComponent;

	ButtonWidget m_CreateGroupButton;
	SCR_ModularButtonComponent m_CreateGroupButtonComponent;

	bool Init(Widget root)
	{
		m_GroupListLayout = VerticalLayoutWidget.Cast(root.FindWidget("VerticalLayout0.m_GroupListLayout"));

		m_GroupNameEditBox = ButtonWidget.Cast(root.FindWidget("VerticalLayout0.CreateGroup.m_GroupNameEditBox"));
		m_GroupNameEditBoxComponent = SCR_EditBoxComponent.Cast(m_GroupNameEditBox.FindHandler(SCR_EditBoxComponent));

		m_CreateGroupButton = ButtonWidget.Cast(root.FindWidget("VerticalLayout0.CreateGroup.m_CreateGroupButton"));
		m_CreateGroupButtonComponent = SCR_ModularButtonComponent.Cast(m_CreateGroupButton.FindHandler(SCR_ModularButtonComponent));

		return true;
	}
}
