// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/DeploymentMenu/GroupMemberLine.layout

class PR_GroupMemberLineWidgets
{
	static const ResourceName s_sLayout = "{045345094C0BD150}UI/DeploymentMenu/GroupMemberLine.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_PlayerNameText;

	TextWidget m_RoleNameText;

	bool Init(Widget root)
	{
		m_PlayerNameText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.m_PlayerNameText"));

		m_RoleNameText = TextWidget.Cast(root.FindWidget("HorizontalLayout0.RoleName.m_RoleNameText"));

		return true;
	}
}
