// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/DeploymentMenu/MapInfoBar.layout

class PR_MapInfoBarWidgets
{
	static const ResourceName s_sLayout = "{E96FBDA051C03B2B}UI/DeploymentMenu/MapInfoBar.layout";
	ResourceName GetLayout() { return s_sLayout; }

	HorizontalLayoutWidget m_ContentRoot;

	ImageWidget m_FactionFlagImage;

	TextWidget m_FactionPointsText;

	bool Init(Widget root)
	{
		m_ContentRoot = HorizontalLayoutWidget.Cast(root.FindWidget("m_ContentRoot"));

		m_FactionFlagImage = ImageWidget.Cast(root.FindWidget("m_ContentRoot.m_FactionFlagImage"));

		m_FactionPointsText = TextWidget.Cast(root.FindWidget("m_ContentRoot.m_FactionPointsText"));

		return true;
	}
}
