// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/DeploymentMenu/RoleEntry.layout

class PR_RoleEntryWidgets
{
	static const ResourceName s_sLayout = "{D734BA5F9FB4DC5A}UI/DeploymentMenu/RoleEntry.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_RoleName;

	TextWidget m_RolePrimary;

	TextWidget m_RoleSecondary;

	TextWidget m_RoleAvailability;

	bool Init(Widget root)
	{
		m_RoleName = TextWidget.Cast(root.FindWidget("SizeConstraint.LineContent.HorizontalLayout0.LineElements.m_RoleName"));

		m_RolePrimary = TextWidget.Cast(root.FindWidget("SizeConstraint.LineContent.HorizontalLayout0.LineElements.m_RolePrimary"));

		m_RoleSecondary = TextWidget.Cast(root.FindWidget("SizeConstraint.LineContent.HorizontalLayout0.LineElements.m_RoleSecondary"));

		m_RoleAvailability = TextWidget.Cast(root.FindWidget("SizeConstraint.LineContent.HorizontalLayout0.Right.VerticalLayout.m_RoleAvailability"));

		return true;
	}
}
